[package]
name = "neural_network"
version = "0.1.0"
edition = "2021"
description = "A simple neural network implementation in Rust"
license = "MIT"

[dependencies]
crossterm = "0.28.1"
rand = "0.9.0"
